### ISSUE TITLE
Image not showing up on Podcast page

### ISSUE THREAD

**Issue by miller-productions** [arshad/gatsby-themes#10]
Hi there,

Just noticed that the image isn't displayed for the Podcast page.

Here is a screenshot from a fresh install and `gatsby develop` based on `gatsby new site arshad/gatsby-starter-phoenix`

![image](https://user-images.githubusercontent.com/15177547/71575246-63c55700-2b40-11ea-9bae-2ed4e236ecc2.png)

**Comment by kieranklaassen** [comment]
works for me

**Comment by miller-productions** [comment]
Hmmm, thanks for the heads up @kieranklaassen.

I'll try again on a different machine tomorrow with a fresh clone.

**Comment by arshad** [comment]
@miller-productions Make sure your image is in `assets/images` and the path is set for `@arshad/gatsby-theme-podcast-core`

https://github.com/arshad/gatsby-themes/blob/91b1137bc3077da7693a6e30815f6c9c5d8a0554/examples/gatsby-example-phoenix/gatsby-config.js#L68-L88

**Comment by miller-productions** [comment]
Hi there,

Just tried it out... new machine, fresh vanilla install, didn't change a thing, same result...

Commands were:

`gatsby new phoenix-test arshad/gatsby-starter-phoenix`

`cd phoenix-test`

`mv .env.example .env`

`gatsby develop`

Images are there for all other pages, just not for the podcast page.

Here is `gatsby-config.js`

![image](https://user-images.githubusercontent.com/15177547/72932348-b1398a80-3db3-11ea-8d90-5dca5e98efe3.png)

Here is the podcast page...

![image](https://user-images.githubusercontent.com/15177547/72932382-cadad200-3db3-11ea-9935-78d343811504.png)

Blog page is fine...

![image](https://user-images.githubusercontent.com/15177547/72932411-de863880-3db3-11ea-8ef4-2a66b3988bad.png)

Portfolio page is fine (_note, you have spelling error in the nav menu_)

![image](https://user-images.githubusercontent.com/15177547/72932491-ff4e8e00-3db3-11ea-9f70-a74c569a12a8.png)

Photography page is fine...

![image](https://user-images.githubusercontent.com/15177547/72932554-19886c00-3db4-11ea-98d2-983b56ac4b85.png)
