### ISSUE TITLE
RSS feed not working

### ISSUE THREAD

**Issue by miller-productions** [arshad/gatsby-themes#11]
Hi there, 

Noticed that the RSS feed isn't working.

Here is a screenshot from a fresh install and `gatsby develop` based on `gatsby new site arshad/gatsby-starter-phoenix`

![image](https://user-images.githubusercontent.com/15177547/71612011-6764e680-2bf1-11ea-9099-3557181df7cb.png)

**Comment by arshad** [comment]
The RSS feed is built in production mode only. 

See the note (in the footer) on https://www.gatsbyjs.org/packages/gatsby-plugin-feed/

> NOTE: This plugin only generates the xml file(s) when run in production mode! To test your feed, run: gatsby build && gatsby serve.

**Comment by miller-productions** [comment]
Sorry, silly me. 😂
