### ISSUE TITLE
Gatsby and React Dev Dependencies hard-coded versions instead of range

### ISSUE THREAD

**Issue by tedyoung** [arshad/gatsby-themes#31]
It looks like the themes have dependencies on very specific versions of React and Gatsby. This means that when I have version 2.19.24 of Gatsby, I'll get a warning because that's "not compatible" with the precise 2.19.12 version specified by the themes.

Would it be possible to change the versions to be `~2.19.12` (using the `~` for patch range) so as to not trigger this warning? Unless the themes truly _require_ 2.19.12?

**Comment by arshad** [comment]
This is definitely something I'm looking into. 

The idea was to have the dependencies pinned then create PRs using `renovate` bot to update versions. This would make it easy to test minor version of Gatsby. 

But all this is just planned and not implemented yet 😁

**Comment by tedyoung** [comment]
Gotcha. Patch level (tilde) would be useful in the meantime.
