### ISSUE TITLE
Sub-pages are not working 

### ISSUE THREAD

**Issue by mattmaker** [arshad/gatsby-themes#38]
I am trying to create sub-pages but keep getting the 404 page.

I have a page folder called "Services" and I created a folder in that one which contains an index.mdx file.

I added `path: "page-title"` in Frontmatter and pushed to GitHub, which deployed to Netlify.

When I visit the website on the Netlify subdomain and click on the Services page, it works.

But when I click the link to the sub-page it takes me to the 404 page.

I even tried manually typing in the URL to the subpage and the same thing happened.

Any idea what could be wrong?

**Comment by arshad** [comment]
@mattmaker is this happening on Netlify only? Does it work on local?

**Comment by arshad** [comment]
Oh you actually need `slug` and not `path`. Does this work?

```mdx
---
title: Services
excerpt: Our Services
slug: "page-title"
---
```

**Comment by mattmaker** [comment]
@arshad Yes! Using `slug` instead of `path` worked!

**Comment by arshad** [comment]
@mattmaker OK to close this one?
