### ISSUE TITLE
GRAPHQL ERROR #85901 

### ISSUE THREAD

**Issue by mattmaker** [arshad/gatsby-themes#44]
For some reason I keep getting this error when I run `gatsby develop`:

````
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Float cannot represent non numeric value: Infinity

   1 | query usersmattSitesMySitesrcgatsbyThemeFlexcomponentsimageJs3510508003 {
   2 |   allFile(filter: {sourceInstanceName: {eq: "image"}}) {
   3 |     images: nodes {
   4 |       relativePath
   5 |       src: childImageSharp {
   6 |         fluid(cropFocus: CENTER, quality: 100) {
   7 |           base64
>  8 |           aspectRatio
     |           ^
   9 |           src
  10 |           srcSet
  11 |           srcWebp
  12 |           srcSetWebp
  13 |           sizes
  14 |         }
  15 |       }
  16 |     }
  17 |   }
  18 | }

File path: ../MySite/src/gatsby-theme-flex/components/image.js
Plugin: none
````

I have no clue what the problem could be.

Any help?

**Comment by arshad** [comment]
Is this happening for all images? or a recently added image? Anyway we can trace back to which file this is happening?

**Comment by mattmaker** [comment]
All the images on the site are working fine. I tried creating a new site with
 `gatsby new site arshad/gatsby-starter-flex`
and copied over files from the original site one by one and used `gatsby develop` every time.

I thought that would help pinpoint the problem. But unfortunately I couldn't find where it was coming from :(

I'm not too good with GraphQL either and when it says
 `Float cannot represent non numeric value: Infinity`
I don't know what it means.

I even did `gatsby clean` before `gatsby develop` and it made no difference.

**Comment by mattmaker** [comment]
I fixed it!

So I searched through the files for `3510508003` which is the last part of the query on line 1. It led me to this file `public/static/d/3510508003.json`.

I saw some image paths listed and noticed one of them was an image I wasn't using. I simply deleted it from the assets/images folder and ran `gatsby develop` again and the problem magically went away lol.

**Comment by arshad** [comment]
Nice. I'm going to close this one. Thanks.
