### ISSUE TITLE
How to override tailwind.config.js

### ISSUE THREAD

**Issue by oefterdal** [arshad/gatsby-themes#48]
I am trying to change theme colors, but can't figure out how I override the theme colors.

**Comment by arshad** [comment]
You can [shadow](https://www.gatsbyjs.org/docs/themes/shadowing/) the Phoenix `tailwind.config.js` file and tell webpack to use it.

1. Create the following file in your Gatsby site: `src/@arshad/gatsby-theme-phoenix/tailwind.config.js`

2. Add the following to your `gatsby-config.js`:

```js
{
  resolve: `gatsby-plugin-postcss`,
  options: {
    postCssPlugins: [
      require("tailwindcss")(require("./src/@arshad/gatsby-theme-phoenix/tailwind.config")),
      require("autoprefixer"),
      require("postcss-color-function"),
    ],
  },
},
```

3. Restart `gatsby develop`

You can extend and overwrite the default Phoenix tailwind config as follows:

```js
// src/@arshad/gatsby-theme-phoenix/tailwind.config.js

const merge = require("deepmerge")
const base = require("@arshad/gatsby-theme-phoenix/src/tailwind.config")

module.exports = merge(base, {
  theme: {
    colors: {
      primary: "#f30",
    }
  }
})
```

**Comment by oefterdal** [comment]
Thank you.
