### ISSUE TITLE
Missing blocks 

### ISSUE THREAD

**Issue by oefterdal** [arshad/gatsby-themes#50]
I was looking on your demo https://flex.arshad.io/blocks 
But I can't find the blocks for Text, "Text and Image"  and "Image and Text".

**Comment by arshad** [comment]
This is a `Feature` block.

```md
<Feature
  heading="Text and Image"
  lead="Nesciunt sunt voluptas. Fugit perferendis labore placeat dolorem corporis."
  imageUrl="placeholder.jpg"
  imagePosition="right"
  links={<><Button>Get Started</Button> <Button type="secondary">Learn more</Button></>}
  style={{
    bg: "muted"
  }}
>
```

You can find the repo and example pages here: https://github.com/arshad/gatsby-example-flex/tree/master/content/pages

**Comment by oefterdal** [comment]
Thank you.
