### ISSUE TITLE
How do I enable prisma code highlighting?

### ISSUE THREAD

**Issue by sharduul** [arshad/gatsby-themes#54]
The [readme](https://github.com/arshad/gatsby-themes) doc says the pages supports code highlighting with prismjs.

But, my home page looks like this

![Screen Shot 2020-04-26 at 6 56 28 PM](https://user-images.githubusercontent.com/4227876/80327164-0b514e00-87f0-11ea-9aec-a9f649844f74.png)

I have included the `@arshad/gatsby-theme-page-core` in my list of plugins.

Do I need to install anything else or do I need some custom config setting?

**Comment by arshad** [comment]
It looks like there was a regression when we integrated with flex. I've added syntax highlighting back. 

A quick `npm update` then `gatsby clean` should fix this.
