### ISSUE TITLE
YouTube Streaming?

### ISSUE THREAD

**Issue by rogersaz** [arshad/gatsby-themes#64]
What would be the best way to add to MY website a Youtube Stream from MY YouTube Page? I'm looking at dependencies "gatsby-source-youtube-v2" but the Docs. do not say anything about streaming? Can I just add an iFrame link to the MDX file and call it good or is there a better way? I've been reading that the best way is to use the channel ID because if you use an API with YouTube streaming if the feed is dropped at any time YouTube will generate a new API?

**Comment by arshad** [comment]
Yeah an iframe with `https://www.youtube.com/embed/live_stream?channel=CHANNEL_ID` should work.

**Comment by rogersaz** [comment]
thanks I like to keep it simple :-)
