### ISSUE TITLE
Commenting System

### ISSUE THREAD

**Issue by 5parkp1ug** [arshad/gatsby-themes#65]
Is there any way we could implement commenting system for the blog posts like the ones provided by gatsby. I was looking to implement Disqus commenting system but not sure about how to begin with while using Phoenix theme. Any help would be highly appreciated.

**Comment by arshad** [comment]
Sure. Let me take a look.

**Comment by arshad** [comment]
@5parkp1ug OK I created a quick demo.

- Demo: https://gatsby-theme-phoenix-disqus.netlify.app/blog/2019-10-11-proident-enim-aliqua
- Example repo: https://github.com/arshad/gatsby-theme-phoenix-disqus

Take a look at the README. 

Let me know if this works.

**Comment by 5parkp1ug** [comment]
Thanks! I will check and let you know ASAP! 👍

**Comment by 5parkp1ug** [comment]
Thanks a lot @arshad. It's working fine.
