### ISSUE TITLE
Adding Algolia Search to theme

### ISSUE THREAD

**Issue by f1ps** [arshad/gatsby-themes#67]
First love your Themes! Are there plans to include Algolia Search to your themes? That would be super amazing!

**Comment by arshad** [comment]
Thank you. Really appreciate the kind words.

Which theme are you integrating Algolia Search with? Flex or Phoenix?

We are working on the next version for Flex. We'll add support for Algolia Search.

If you need it for Phoenix, I could add some pointers here.

**Comment by f1ps** [comment]
Phoenix 😅

**Comment by f1ps** [comment]
Will the next version of Flex include a blog post section?

**Comment by arshad** [comment]
> Phoenix 😅

Let me see how we can add algolia to this one.

> Will the next version of Flex include a blog post section?

Yes. It will include a customizable blog theme.

**Comment by f1ps** [comment]
> Let me see how we can add algolia to this one.

would be super cool!

**Comment by f1ps** [comment]
I'm still interested to add Algolia Search

**Comment by arshad** [comment]
Sure. I'll take a look at this again. I got Algolia working but not themed yet.

**Comment by f1ps** [comment]
Hey @arshad,

I just saw your tweet about https://reflexjs.org/ so please put your valuable time on this amazing theme framework and when the Algolia search is added there I will migrate my previous customizations from Phoenix over! 

Is there a possibility to support this wonderful work? Patreon? 

Best
Philip

**Comment by arshad** [comment]
@f1ps Thank you. Yeah Reflex got some amazing feedback. I have not thought about sponsors for now. Thinking about growing the project more. Thanks so much though. This is the kind of validation I was looking for when launching the developer preview. :D
