### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by 5parkp1ug** [arshad/gatsby-themes#68]
Hi @arshad, 

I was trying to add emoji support via the plugin [gatsby-remark-emojis](https://www.gatsbyjs.org/packages/gatsby-remark-emojis/?=emoji) but the emojis are not getting rendered. Could you please help?

TIA & Regards

**Comment by arshad** [comment]
Sure. I'll take a look.

**Comment by arshad** [comment]
@5parkp1ug You can use it as a `remark` plugin for mdx.

Install `remark-emoji`

`npm i remark-emoji`

then in your site's `gatsby-config.js`

```js
plugins: [
   ...
   `@arshad/gatsby-theme-blog-core`,
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        remarkPlugins: [require(`remark-emoji`)],
      },
    },
   ...
]
```

**Comment by 5parkp1ug** [comment]
@arshad Its is working!!! You are champ :) Thanks a lot!

**Comment by 5parkp1ug** [comment]
However, the images are not getting loaded from my mdx files now! :/

**Comment by arshad** [comment]
Hmm can you try the following:

```js
const coreBlogConfig = require("@arshad/gatsby-theme-blog-core/gatsby-config.js")(
  {}
).plugins.find(i => i.resolve == "gatsby-plugin-mdx")

module.exports = {
  plugins: [
    ...
    `@arshad/gatsby-theme-blog-core`,
      {
        resolve: `gatsby-plugin-mdx`,
        options: {
          ...coreBlogConfig.options, <----- I added this line
          remarkPlugins: [require(`remark-emoji`)],
        },
      },
    ...
  ]
}
```

**Comment by 5parkp1ug** [comment]
Nope still not working.... In fact the images are not loading at all! :(

**Comment by arshad** [comment]
Not stale. 

(Been busy with some other project. I'll take a look at this again this week)
