### ISSUE TITLE
A question about gatsby-theme-flex

### ISSUE THREAD

**Issue by murilinhoPs** [arshad/gatsby-themes#74]
I wanted to know if there is a way to change the directory where it gets the page. The default is: content/pages, for example can I change to: src/content/pages?

**Comment by arshad** [comment]
Sure. In your `gatsby-config.js` file:

Replace 

https://github.com/arshad/gatsby-themes/blob/d79ed80afa84101e7a5a7ed16abb2695a247da9b/themes/gatsby-theme-flex/gatsby-config.js#L26-L27

With

```
plugins: [
  {
    resolve: `@arshad/gatsby-theme-page-core`,
    options: {
      contentPath: `src/content/pages`,
    }
  },
]
```

**Comment by murilinhoPs** [comment]
Thanks for helping me! Closing the issue
