### ISSUE TITLE
rss.xml url problem

### ISSUE THREAD

**Issue by woosungchoi** [arshad/gatsby-themes#76]
I am using your phoenix theme well. However, I would like to discover that there is an rss problem and suggest a solution.

First, install gatsby-plugin-feed.

```
npm install gatsby-plugin-feed --save
```

and

1. change rss url

https://github.com/arshad/gatsby-themes/blob/master/themes/gatsby-theme-phoenix/src/components/header.js#L53

from {href="/rss.xml"} to {href="/blog/rss.xml}

It's my commit.

https://github.com/woosungchoi/gatsby-starter-phoenix/commit/4d14d4c22248123d81a11284e9fb55d44b1515c2

2. Replace url when creating rss.xml.

Actually, I am not sure how to do this.

Please solve the rss problem.

**Comment by arshad** [comment]
Nice catch. I'll fix this. Thank you.
