### ISSUE TITLE
browser title problem when access blog page

### ISSUE THREAD

**Issue by woosungchoi** [arshad/gatsby-themes#77]
When you access a blog page, the title of the browser displays the site title as a duplicate.

https://arshad-gatsby-example-phoenix.netlify.app/blog/2019-10-11-proident-enim-aliqua

![blog-title](https://user-images.githubusercontent.com/5674610/87248276-9fe45780-c493-11ea-919c-81003e48ef62.png)

**Comment by icheft** [comment]
Same concern here 🙌🏾
